<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('language_configs', function (Blueprint $table) {
            $table->id();
            $table->string('param');
            $table->text('title')->nullable();
            $table->string('language');
            $table->string('page_control')->nullable();
            $table->timestamps();
            $table->unique(['param', 'language']);
        });

        DB::table('language_configs')->insert([
            ['param' => 'u1VNlE6GGA9GRwU', 'title' => 'ชื่อ', 'language' => 'th', 'page_control' => '20'],
            ['param' => 'u1VNlE6GGA9GRwU', 'title' => 'Name', 'language' => 'en', 'page_control' => '20'],
            ['param' => 'u1VNlE6GGA9GRwU', 'title' => 'Name', 'language' => 'kh', 'page_control' => '20'],
            ['param' => 'u1VNlE6GGA9GRwU', 'title' => 'Name', 'language' => 'ind', 'page_control' => '20'],
            ['param' => '6ZmmoqU8PnKBjdR', 'title' => 'อีเมล', 'language' => 'th', 'page_control' => '20'],
            ['param' => '6ZmmoqU8PnKBjdR', 'title' => 'E-mail', 'language' => 'en', 'page_control' => '20'],
            ['param' => '6ZmmoqU8PnKBjdR', 'title' => 'E-mail', 'language' => 'kh', 'page_control' => '20'],
            ['param' => '6ZmmoqU8PnKBjdR', 'title' => 'E-mail', 'language' => 'ind', 'page_control' => '20'],
            ['param' => 'fg0zoRDFPOu9G5J', 'title' => 'ไลน์ไอดี', 'language' => 'th', 'page_control' => '20'],
            ['param' => 'fg0zoRDFPOu9G5J', 'title' => 'Line ID', 'language' => 'en', 'page_control' => '20'],
            ['param' => 'fg0zoRDFPOu9G5J', 'title' => 'Line ID', 'language' => 'kh', 'page_control' => '20'],
            ['param' => 'fg0zoRDFPOu9G5J', 'title' => 'Line ID', 'language' => 'ind', 'page_control' => '20'],
            ['param' => 'r1xGQX3ouMMsikn', 'title' => 'เบอร์โทร', 'language' => 'th', 'page_control' => '20'],
            ['param' => 'r1xGQX3ouMMsikn', 'title' => 'Phone number', 'language' => 'en', 'page_control' => '20'],
            ['param' => 'r1xGQX3ouMMsikn', 'title' => 'Phone number', 'language' => 'kh', 'page_control' => '20'],
            ['param' => 'r1xGQX3ouMMsikn', 'title' => 'Phone number', 'language' => 'ind', 'page_control' => '20'],
            ['param' => 'ovlgbe5QQYjnRdV', 'title' => 'รหัสผ่าน', 'language' => 'th', 'page_control' => '20'],
            ['param' => 'ovlgbe5QQYjnRdV', 'title' => 'Password', 'language' => 'en', 'page_control' => '20'],
            ['param' => 'ovlgbe5QQYjnRdV', 'title' => 'Password', 'language' => 'kh', 'page_control' => '20'],
            ['param' => 'ovlgbe5QQYjnRdV', 'title' => 'Password', 'language' => 'ind', 'page_control' => '20'],
            ['param' => 'OM8Jr7JsPn1kkiY', 'title' => 'ยืนยันรหัสผ่าน', 'language' => 'th', 'page_control' => '20'],
            ['param' => 'OM8Jr7JsPn1kkiY', 'title' => 'Confirm Password', 'language' => 'en', 'page_control' => '20'],
            ['param' => 'OM8Jr7JsPn1kkiY', 'title' => 'Confirm Password', 'language' => 'kh', 'page_control' => '20'],
            ['param' => 'OM8Jr7JsPn1kkiY', 'title' => 'Confirm Password', 'language' => 'ind', 'page_control' => '20'],
            ['param' => '599p8c8jsIxU0ql', 'title' => 'สมัครสมาชิก', 'language' => 'th', 'page_control' => '20'],
            ['param' => '599p8c8jsIxU0ql', 'title' => 'SIGN UP', 'language' => 'en', 'page_control' => '20'],
            ['param' => '599p8c8jsIxU0ql', 'title' => 'SIGN UP', 'language' => 'kh', 'page_control' => '20'],
            ['param' => '599p8c8jsIxU0ql', 'title' => 'SIGN UP', 'language' => 'ind', 'page_control' => '20'],
            ['param' => '1adeTO2gojB2ilw', 'title' => 'ยอมรับข้อกำหนดในการให้บริการและนโยบายความเป็นส่วนตัว', 'language' => 'th', 'page_control' => '20'],
            ['param' => '1adeTO2gojB2ilw', 'title' => 'Agree to Terms of Service and Privacy Policy', 'language' => 'en', 'page_control' => '20'],
            ['param' => '1adeTO2gojB2ilw', 'title' => 'Agree to Terms of Service and Privacy Policy', 'language' => 'kh', 'page_control' => '20'],
            ['param' => '1adeTO2gojB2ilw', 'title' => 'Agree to Terms of Service and Privacy Policy', 'language' => 'ind', 'page_control' => '20'],
            ['param' => '1iYRQlv6cdipsOK', 'title' => 'มีบัญชีอยู่แล้ว?', 'language' => 'th', 'page_control' => '20'],
            ['param' => '1iYRQlv6cdipsOK', 'title' => 'Already have an account?', 'language' => 'en', 'page_control' => '20'],
            ['param' => '1iYRQlv6cdipsOK', 'title' => 'Already have an account?', 'language' => 'kh', 'page_control' => '20'],
            ['param' => '1iYRQlv6cdipsOK', 'title' => 'Already have an account?', 'language' => 'ind', 'page_control' => '20'],
            ['param' => 'uuIcJxsfRL2KrA4', 'title' => 'เข้าสู่ระบบ', 'language' => 'th', 'page_control' => '20'],
            ['param' => 'uuIcJxsfRL2KrA4', 'title' => 'LOGIN', 'language' => 'en', 'page_control' => '20'],
            ['param' => 'uuIcJxsfRL2KrA4', 'title' => 'LOGIN', 'language' => 'kh', 'page_control' => '20'],
            ['param' => 'uuIcJxsfRL2KrA4', 'title' => 'LOGIN', 'language' => 'ind', 'page_control' => '20'],
            ['param' => 'mWknhrfWv6PwDmn', 'title' => 'ชื่อ', 'language' => 'th', 'page_control' => '19'],
            ['param' => 'mWknhrfWv6PwDmn', 'title' => 'Name', 'language' => 'en', 'page_control' => '19'],
            ['param' => 'mWknhrfWv6PwDmn', 'title' => 'Name', 'language' => 'kh', 'page_control' => '19'],
            ['param' => 'mWknhrfWv6PwDmn', 'title' => 'Name', 'language' => 'ind', 'page_control' => '19'],
            ['param' => 'oqDOCTJhyfiUGKk', 'title' => 'รหัสผ่าน', 'language' => 'th', 'page_control' => '19'],
            ['param' => 'oqDOCTJhyfiUGKk', 'title' => 'Password', 'language' => 'en', 'page_control' => '19'],
            ['param' => 'oqDOCTJhyfiUGKk', 'title' => 'Password', 'language' => 'kh', 'page_control' => '19'],
            ['param' => 'oqDOCTJhyfiUGKk', 'title' => 'Password', 'language' => 'ind', 'page_control' => '19'],
            ['param' => '4MvipEFalEb7VGl', 'title' => 'เข้าสู่ระบบ', 'language' => 'th', 'page_control' => '19'],
            ['param' => '4MvipEFalEb7VGl', 'title' => 'LOGIN', 'language' => 'en', 'page_control' => '19'],
            ['param' => '4MvipEFalEb7VGl', 'title' => 'LOGIN', 'language' => 'kh', 'page_control' => '19'],
            ['param' => '4MvipEFalEb7VGl', 'title' => 'LOGIN', 'language' => 'ind', 'page_control' => '19'],
            ['param' => 'w7GiRktRhYFXMnt', 'title' => 'ลืมรหัสผ่าน?', 'language' => 'th', 'page_control' => '19'],
            ['param' => 'w7GiRktRhYFXMnt', 'title' => 'Forgot password?', 'language' => 'en', 'page_control' => '19'],
            ['param' => 'w7GiRktRhYFXMnt', 'title' => 'Forgot password?', 'language' => 'kh', 'page_control' => '19'],
            ['param' => 'w7GiRktRhYFXMnt', 'title' => 'Forgot password?', 'language' => 'ind', 'page_control' => '19'],
            ['param' => 'y3WrYXiFdyNobSR', 'title' => 'ยังไม่ได้เป็นสมาชิก?', 'language' => 'th', 'page_control' => '19'],
            ['param' => 'y3WrYXiFdyNobSR', 'title' => 'Not a member yet?', 'language' => 'en', 'page_control' => '19'],
            ['param' => 'y3WrYXiFdyNobSR', 'title' => 'Not a member yet?', 'language' => 'kh', 'page_control' => '19'],
            ['param' => 'y3WrYXiFdyNobSR', 'title' => 'Not a member yet?', 'language' => 'ind', 'page_control' => '19'],
            ['param' => 'dyhF0VX3CirDm7Z', 'title' => 'สมัครสมาชิกที่นี่', 'language' => 'th', 'page_control' => '19'],
            ['param' => 'dyhF0VX3CirDm7Z', 'title' => 'SIGN UP HERE', 'language' => 'en', 'page_control' => '19'],
            ['param' => 'dyhF0VX3CirDm7Z', 'title' => 'SIGN UP HERE', 'language' => 'kh', 'page_control' => '19'],
            ['param' => 'dyhF0VX3CirDm7Z', 'title' => 'SIGN UP HERE', 'language' => 'ind', 'page_control' => '19'],
            ['param' => 'Cq9xdCyinuQ4M08', 'title' => 'ซัก  & อบผ้า', 'language' => 'th', 'page_control' => '22'],
            ['param' => 'Cq9xdCyinuQ4M08', 'title' => 'WASH & DRY', 'language' => 'en', 'page_control' => '22'],
            ['param' => 'Cq9xdCyinuQ4M08', 'title' => 'WASH & DRY', 'language' => 'kh', 'page_control' => '22'],
            ['param' => 'Cq9xdCyinuQ4M08', 'title' => 'WASH & DRY', 'language' => 'ind', 'page_control' => '22'],
            ['param' => 'p7NhmzzCKEZHr5a', 'title' => 'อาหาร & เครื่องดื่ม', 'language' => 'th', 'page_control' => '22'],
            ['param' => 'p7NhmzzCKEZHr5a', 'title' => 'VENDING & CAFE', 'language' => 'en', 'page_control' => '22'],
            ['param' => 'p7NhmzzCKEZHr5a', 'title' => 'VENDING & CAFE', 'language' => 'kh', 'page_control' => '22'],
            ['param' => 'p7NhmzzCKEZHr5a', 'title' => 'VENDING & CAFE', 'language' => 'ind', 'page_control' => '22'],
            ['param' => '3HgYorJLAMxNleL', 'title' => 'เลือกภาษา', 'language' => 'th', 'page_control' => '22'],
            ['param' => '3HgYorJLAMxNleL', 'title' => 'Language', 'language' => 'en', 'page_control' => '22'],
            ['param' => '3HgYorJLAMxNleL', 'title' => 'Language', 'language' => 'kh', 'page_control' => '22'],
            ['param' => '3HgYorJLAMxNleL', 'title' => 'Language', 'language' => 'ind', 'page_control' => '22'],
            ['param' => '3yRRcWdpAevbBQz', 'title' => 'เงื่อนไขการให้บริการ', 'language' => 'th', 'page_control' => '22'],
            ['param' => '3yRRcWdpAevbBQz', 'title' => 'Terms of Service', 'language' => 'en', 'page_control' => '22'],
            ['param' => '3yRRcWdpAevbBQz', 'title' => 'Terms of Service', 'language' => 'kh', 'page_control' => '22'],
            ['param' => '3yRRcWdpAevbBQz', 'title' => 'Terms of Service', 'language' => 'ind', 'page_control' => '22'],
            ['param' => '9o3ier2Fyu5Nscp', 'title' => 'นโยบายความเป็นส่วนตัว', 'language' => 'th', 'page_control' => '22'],
            ['param' => '9o3ier2Fyu5Nscp', 'title' => 'Privacy Policy', 'language' => 'en', 'page_control' => '22'],
            ['param' => '9o3ier2Fyu5Nscp', 'title' => 'Privacy Policy', 'language' => 'kh', 'page_control' => '22'],
            ['param' => '9o3ier2Fyu5Nscp', 'title' => 'Privacy Policy', 'language' => 'ind', 'page_control' => '22'],
            ['param' => 'aBtjDb1h65e4rii', 'title' => 'ที่อยู่รับ - จัดส่ง', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'aBtjDb1h65e4rii', 'title' => 'Address drop off and pick up', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'aBtjDb1h65e4rii', 'title' => 'Address drop off and pick up', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'aBtjDb1h65e4rii', 'title' => 'Address drop off and pick up', 'language' => 'ind', 'page_control' => '9'],
            ['param' => '5AD9NMb52XVVsp', 'title' => 'รับ', 'language' => 'th', 'page_control' => '9'],
            ['param' => '5AD9NMb52XVVsp', 'title' => 'Pick up', 'language' => 'en', 'page_control' => '9'],
            ['param' => '5AD9NMb52XVVsp', 'title' => 'Pick up', 'language' => 'kh', 'page_control' => '9'],
            ['param' => '5AD9NMb52XVVsp', 'title' => 'Pick up', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'GGcdV5UPmpc316c', 'title' => 'จัดส่ง', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'GGcdV5UPmpc316c', 'title' => 'Drop off', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'GGcdV5UPmpc316c', 'title' => 'Drop off', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'GGcdV5UPmpc316c', 'title' => 'Drop off', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'TuYcb5eDJauPaQu', 'title' => 'เบอร์โทร', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'TuYcb5eDJauPaQu', 'title' => 'Your Phone Number', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'TuYcb5eDJauPaQu', 'title' => 'Your Phone Number', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'TuYcb5eDJauPaQu', 'title' => 'Your Phone Number', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'Vbegqwl9kN80ROY', 'title' => '*รายละเอียด', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'Vbegqwl9kN80ROY', 'title' => '*Detail List', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'Vbegqwl9kN80ROY', 'title' => '*Detail List', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'Vbegqwl9kN80ROY', 'title' => '*Detail List', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'NbYnxbNcZntOw6o', 'title' => 'เลือกสาขา', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'NbYnxbNcZntOw6o', 'title' => 'Choose a Branch', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'NbYnxbNcZntOw6o', 'title' => 'Choose a Branch', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'NbYnxbNcZntOw6o', 'title' => 'Choose a Branch', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'B0wtvvlbp1677sp', 'title' => 'เลือกเวลารับ - ส่ง', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'B0wtvvlbp1677sp', 'title' => 'Pick-up time', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'B0wtvvlbp1677sp', 'title' => 'Pick-up time', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'B0wtvvlbp1677sp', 'title' => 'Pick-up time', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'V8Ho6eF0aGr2irv', 'title' => 'เวลาปัจจุบัน', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'V8Ho6eF0aGr2irv', 'title' => 'Now', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'V8Ho6eF0aGr2irv', 'title' => 'Now', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'V8Ho6eF0aGr2irv', 'title' => 'Now', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'PoiTgc3MaWyc6PA', 'title' => 'เวลารับ', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'PoiTgc3MaWyc6PA', 'title' => 'Pick up', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'PoiTgc3MaWyc6PA', 'title' => 'Pick up', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'PoiTgc3MaWyc6PA', 'title' => 'Pick up', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'YRqOsqSBJNXyAuF', 'title' => 'เวลาส่ง', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'YRqOsqSBJNXyAuF', 'title' => 'Drop off', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'YRqOsqSBJNXyAuF', 'title' => 'Drop off', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'YRqOsqSBJNXyAuF', 'title' => 'Drop off', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'tdEoWeUUPGF7TSk', 'title' => 'เลือกวันที่และเวลา :', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'tdEoWeUUPGF7TSk', 'title' => 'Select a date and time :', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'tdEoWeUUPGF7TSk', 'title' => 'Select a date and time :', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'tdEoWeUUPGF7TSk', 'title' => 'Select a date and time :', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'LXMrq1BKzFQqZnA', 'title' => 'เลือกเวลา', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'LXMrq1BKzFQqZnA', 'title' => 'Select a time', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'LXMrq1BKzFQqZnA', 'title' => 'Select a time', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'LXMrq1BKzFQqZnA', 'title' => 'Select a time', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'HkSjz0iqOdJYYio', 'title' => 'ประเภทผ้า', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'HkSjz0iqOdJYYio', 'title' => 'Clothing type', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'HkSjz0iqOdJYYio', 'title' => 'Clothing type', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'HkSjz0iqOdJYYio', 'title' => 'Clothing type', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'S9VLUBTUcGuzSof', 'title' => 'การซักหรือการอบ', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'S9VLUBTUcGuzSof', 'title' => 'Washing or Drying', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'S9VLUBTUcGuzSof', 'title' => 'Washing or Drying', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'S9VLUBTUcGuzSof', 'title' => 'Washing or Drying', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'PIW1qcSLzU6VRoT', 'title' => 'ถัดไป', 'language' => 'th', 'page_control' => '9'],
            ['param' => 'PIW1qcSLzU6VRoT', 'title' => 'Next', 'language' => 'en', 'page_control' => '9'],
            ['param' => 'PIW1qcSLzU6VRoT', 'title' => 'Next', 'language' => 'kh', 'page_control' => '9'],
            ['param' => 'PIW1qcSLzU6VRoT', 'title' => 'Next', 'language' => 'ind', 'page_control' => '9'],
            ['param' => 'Uq0uPjcGCK5s8ik', 'title' => 'เพิ่มในตะกร้า', 'language' => 'th', 'page_control' => '10'],
            ['param' => 'Uq0uPjcGCK5s8ik', 'title' => 'Add', 'language' => 'en', 'page_control' => '10'],
            ['param' => 'Uq0uPjcGCK5s8ik', 'title' => 'Add', 'language' => 'kh', 'page_control' => '10'],
            ['param' => 'Uq0uPjcGCK5s8ik', 'title' => 'Add', 'language' => 'ind', 'page_control' => '10'],
            ['param' => 'T9etzQlS2d60d2v', 'title' => 'เพิ่มการอบผ้า', 'language' => 'th', 'page_control' => '10'],
            ['param' => 'T9etzQlS2d60d2v', 'title' => 'Add Dry', 'language' => 'en', 'page_control' => '10'],
            ['param' => 'T9etzQlS2d60d2v', 'title' => 'Add Dry', 'language' => 'kh', 'page_control' => '10'],
            ['param' => 'T9etzQlS2d60d2v', 'title' => 'Add Dry', 'language' => 'ind', 'page_control' => '10'],
            ['param' => 'pzrKgXNCLcVWh23', 'title' => 'เวลาการอบ', 'language' => 'th', 'page_control' => '11'],
            ['param' => 'pzrKgXNCLcVWh23', 'title' => 'Drying time', 'language' => 'en', 'page_control' => '11'],
            ['param' => 'pzrKgXNCLcVWh23', 'title' => 'Drying time', 'language' => 'kh', 'page_control' => '11'],
            ['param' => 'pzrKgXNCLcVWh23', 'title' => 'Drying time', 'language' => 'ind', 'page_control' => '11'],
            ['param' => 'ITrjjm7W4nknVDM', 'title' => 'เพิ่มเวลาการอบ', 'language' => 'th', 'page_control' => '11'],
            ['param' => 'ITrjjm7W4nknVDM', 'title' => 'Add Drying time', 'language' => 'en', 'page_control' => '11'],
            ['param' => 'ITrjjm7W4nknVDM', 'title' => 'Add Drying time', 'language' => 'kh', 'page_control' => '11'],
            ['param' => 'ITrjjm7W4nknVDM', 'title' => 'Add Drying time', 'language' => 'ind', 'page_control' => '11'],
            ['param' => 'oLhGryWeJeSpKtP', 'title' => 'นาที', 'language' => 'th', 'page_control' => '11'],
            ['param' => 'oLhGryWeJeSpKtP', 'title' => 'Minute', 'language' => 'en', 'page_control' => '11'],
            ['param' => 'oLhGryWeJeSpKtP', 'title' => 'Minute', 'language' => 'kh', 'page_control' => '11'],
            ['param' => 'oLhGryWeJeSpKtP', 'title' => 'Minute', 'language' => 'ind', 'page_control' => '11'],
            ['param' => 'NLUeqe1kH1RvHcW', 'title' => 'ราคา', 'language' => 'th', 'page_control' => '11'],
            ['param' => 'NLUeqe1kH1RvHcW', 'title' => 'Price', 'language' => 'en', 'page_control' => '11'],
            ['param' => 'NLUeqe1kH1RvHcW', 'title' => 'Price', 'language' => 'kh', 'page_control' => '11'],
            ['param' => 'NLUeqe1kH1RvHcW', 'title' => 'Price', 'language' => 'ind', 'page_control' => '11'],
            ['param' => 'DCPa4kNnQhSoHIO', 'title' => 'ยกเลิกการเพิ่มเวลา', 'language' => 'th', 'page_control' => '11'],
            ['param' => 'DCPa4kNnQhSoHIO', 'title' => 'Cancel add time', 'language' => 'en', 'page_control' => '11'],
            ['param' => 'DCPa4kNnQhSoHIO', 'title' => 'Cancel add time', 'language' => 'kh', 'page_control' => '11'],
            ['param' => 'DCPa4kNnQhSoHIO', 'title' => 'Cancel add time', 'language' => 'ind', 'page_control' => '11'],
            ['param' => 'zU2rZkz1XOoKRvU', 'title' => 'ยืนยันการเพิ่มเวลา', 'language' => 'th', 'page_control' => '11'],
            ['param' => 'zU2rZkz1XOoKRvU', 'title' => 'Confirm add time', 'language' => 'en', 'page_control' => '11'],
            ['param' => 'zU2rZkz1XOoKRvU', 'title' => 'Confirm add time', 'language' => 'kh', 'page_control' => '11'],
            ['param' => 'zU2rZkz1XOoKRvU', 'title' => 'Confirm add time', 'language' => 'ind', 'page_control' => '11'],
            ['param' => 'NWpO8HctXGl4pRo', 'title' => 'เพิ่มในตะกร้า', 'language' => 'th', 'page_control' => '11'],
            ['param' => 'NWpO8HctXGl4pRo', 'title' => 'Add', 'language' => 'en', 'page_control' => '11'],
            ['param' => 'NWpO8HctXGl4pRo', 'title' => 'Add', 'language' => 'kh', 'page_control' => '11'],
            ['param' => 'NWpO8HctXGl4pRo', 'title' => 'Add', 'language' => 'ind', 'page_control' => '11'],
            ['param' => 'nv3bC1sslhJtORf', 'title' => 'รายการ', 'language' => 'th', 'page_control' => '17'],
            ['param' => 'nv3bC1sslhJtORf', 'title' => 'list', 'language' => 'en', 'page_control' => '17'],
            ['param' => 'nv3bC1sslhJtORf', 'title' => 'list', 'language' => 'kh', 'page_control' => '17'],
            ['param' => 'nv3bC1sslhJtORf', 'title' => 'list', 'language' => 'ind', 'page_control' => '17'],
            ['param' => 'qdXfwhf2HWyorZx', 'title' => 'การซัก', 'language' => 'th', 'page_control' => '17'],
            ['param' => 'qdXfwhf2HWyorZx', 'title' => 'Washing', 'language' => 'en', 'page_control' => '17'],
            ['param' => 'qdXfwhf2HWyorZx', 'title' => 'Washing', 'language' => 'kh', 'page_control' => '17'],
            ['param' => 'qdXfwhf2HWyorZx', 'title' => 'Washing', 'language' => 'ind', 'page_control' => '17'],
            ['param' => '1nbuWBfbhmnP9pp', 'title' => 'การอบ', 'language' => 'th', 'page_control' => '17'],
            ['param' => '1nbuWBfbhmnP9pp', 'title' => 'Drying', 'language' => 'en', 'page_control' => '17'],
            ['param' => '1nbuWBfbhmnP9pp', 'title' => 'Drying', 'language' => 'kh', 'page_control' => '17'],
            ['param' => '1nbuWBfbhmnP9pp', 'title' => 'Drying', 'language' => 'ind', 'page_control' => '17'],
            ['param' => 'zXzllHCdt8Yf88l', 'title' => 'รายละเอียด :', 'language' => 'th', 'page_control' => '17'],
            ['param' => 'zXzllHCdt8Yf88l', 'title' => 'Detail List :', 'language' => 'en', 'page_control' => '17'],
            ['param' => 'zXzllHCdt8Yf88l', 'title' => 'Detail List :', 'language' => 'kh', 'page_control' => '17'],
            ['param' => 'zXzllHCdt8Yf88l', 'title' => 'Detail List :', 'language' => 'ind', 'page_control' => '17'],
            ['param' => '7cRkAf4XU4Ntfml', 'title' => 'ราคารวม', 'language' => 'th', 'page_control' => '17'],
            ['param' => '7cRkAf4XU4Ntfml', 'title' => 'Total', 'language' => 'en', 'page_control' => '17'],
            ['param' => '7cRkAf4XU4Ntfml', 'title' => 'Total', 'language' => 'kh', 'page_control' => '17'],
            ['param' => '7cRkAf4XU4Ntfml', 'title' => 'Total', 'language' => 'ind', 'page_control' => '17'],
            ['param' => 'DKRaKGXtC0KH8GS', 'title' => 'เพิ่มรายการ', 'language' => 'th', 'page_control' => '17'],
            ['param' => 'DKRaKGXtC0KH8GS', 'title' => 'Add Order', 'language' => 'en', 'page_control' => '17'],
            ['param' => 'DKRaKGXtC0KH8GS', 'title' => 'Add Order', 'language' => 'kh', 'page_control' => '17'],
            ['param' => 'DKRaKGXtC0KH8GS', 'title' => 'Add Order', 'language' => 'ind', 'page_control' => '17'],
            ['param' => 'LqAJbHs4BBPdMKq', 'title' => 'ยืนยัน', 'language' => 'th', 'page_control' => '17'],
            ['param' => 'LqAJbHs4BBPdMKq', 'title' => 'Confirm', 'language' => 'en', 'page_control' => '17'],
            ['param' => 'LqAJbHs4BBPdMKq', 'title' => 'Confirm', 'language' => 'kh', 'page_control' => '17'],
            ['param' => 'LqAJbHs4BBPdMKq', 'title' => 'Confirm', 'language' => 'ind', 'page_control' => '17'],
            ['param' => 'f5gCBGmueM8bL7O', 'title' => 'เลขออเดอร์', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'f5gCBGmueM8bL7O', 'title' => 'Order Number', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'f5gCBGmueM8bL7O', 'title' => 'Order Number', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'f5gCBGmueM8bL7O', 'title' => 'Order Number', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'jvEyEqILgmusxhe', 'title' => 'ที่อยู่รับ - จัดส่ง', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'jvEyEqILgmusxhe', 'title' => 'Address drop off and pick up', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'jvEyEqILgmusxhe', 'title' => 'Address drop off and pick up', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'jvEyEqILgmusxhe', 'title' => 'Address drop off and pick up', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'PHMksMFwsEdQZmg', 'title' => 'รับ', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'PHMksMFwsEdQZmg', 'title' => 'Pick up', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'PHMksMFwsEdQZmg', 'title' => 'Pick up', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'PHMksMFwsEdQZmg', 'title' => 'Pick up', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'aWKCt5YRkrra8GW', 'title' => 'ส่ง', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'aWKCt5YRkrra8GW', 'title' => 'Drop off', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'aWKCt5YRkrra8GW', 'title' => 'Drop off', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'aWKCt5YRkrra8GW', 'title' => 'Drop off', 'language' => 'ind', 'page_control' => '13'],
            ['param' => '7H8EKBAAbPaBOFl', 'title' => 'เบอร์โทร', 'language' => 'th', 'page_control' => '13'],
            ['param' => '7H8EKBAAbPaBOFl', 'title' => 'Your Phone Number', 'language' => 'en', 'page_control' => '13'],
            ['param' => '7H8EKBAAbPaBOFl', 'title' => 'Your Phone Number', 'language' => 'kh', 'page_control' => '13'],
            ['param' => '7H8EKBAAbPaBOFl', 'title' => 'Your Phone Number', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'dc3lgbeM61vY942', 'title' => 'เลือกสาขา', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'dc3lgbeM61vY942', 'title' => 'Choose a Branch', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'dc3lgbeM61vY942', 'title' => 'Choose a Branch', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'dc3lgbeM61vY942', 'title' => 'Choose a Branch', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'nkd3YdDuTdESvMj', 'title' => 'เวลารับ - ส่ง', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'nkd3YdDuTdESvMj', 'title' => 'Pick-up Time', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'nkd3YdDuTdESvMj', 'title' => 'Pick-up Time', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'nkd3YdDuTdESvMj', 'title' => 'Pick-up Time', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'pEsIJ8yCHqKMLJt', 'title' => 'วันเวลาการรับ - ส่ง', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'pEsIJ8yCHqKMLJt', 'title' => 'Date and Time Pick-up', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'pEsIJ8yCHqKMLJt', 'title' => 'Date and Time Pick-up', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'pEsIJ8yCHqKMLJt', 'title' => 'Date and Time Pick-up', 'language' => 'ind', 'page_control' => '13'],
            ['param' => '1rbNgqKi2Z0RbGA', 'title' => 'รายการทั้งหมด', 'language' => 'th', 'page_control' => '13'],
            ['param' => '1rbNgqKi2Z0RbGA', 'title' => 'List', 'language' => 'en', 'page_control' => '13'],
            ['param' => '1rbNgqKi2Z0RbGA', 'title' => 'List', 'language' => 'kh', 'page_control' => '13'],
            ['param' => '1rbNgqKi2Z0RbGA', 'title' => 'List', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'nrNBgmeaX4VfsCy', 'title' => 'รายการซักและอบ', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'nrNBgmeaX4VfsCy', 'title' => 'Wash and Dry list', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'nrNBgmeaX4VfsCy', 'title' => 'Wash and Dry list', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'nrNBgmeaX4VfsCy', 'title' => 'Wash and Dry list', 'language' => 'ind', 'page_control' => '13'],
            ['param' => '1TuhDnZjqwcomUh', 'title' => 'ซัก', 'language' => 'th', 'page_control' => '13'],
            ['param' => '1TuhDnZjqwcomUh', 'title' => 'Washing', 'language' => 'en', 'page_control' => '13'],
            ['param' => '1TuhDnZjqwcomUh', 'title' => 'Washing', 'language' => 'kh', 'page_control' => '13'],
            ['param' => '1TuhDnZjqwcomUh', 'title' => 'Washing', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'KU3VbuavKrZduwJ', 'title' => 'อบ', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'KU3VbuavKrZduwJ', 'title' => 'Drying', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'KU3VbuavKrZduwJ', 'title' => 'Drying', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'KU3VbuavKrZduwJ', 'title' => 'Drying', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'XL3A1qFyKRUowNi', 'title' => 'นาที', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'XL3A1qFyKRUowNi', 'title' => 'minutes', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'XL3A1qFyKRUowNi', 'title' => 'minutes', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'XL3A1qFyKRUowNi', 'title' => 'minutes', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'qaBfDNm7zjrBSLy', 'title' => 'รายละเอียด', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'qaBfDNm7zjrBSLy', 'title' => 'Detail List', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'qaBfDNm7zjrBSLy', 'title' => 'Detail List', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'qaBfDNm7zjrBSLy', 'title' => 'Detail List', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'PWSMvwRtaU6sSIO', 'title' => 'ราคาสินค้า', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'PWSMvwRtaU6sSIO', 'title' => 'SubTotal', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'PWSMvwRtaU6sSIO', 'title' => 'SubTotal', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'PWSMvwRtaU6sSIO', 'title' => 'SubTotal', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'qsLpFtrvkJon7yW', 'title' => 'ค่าส่ง', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'qsLpFtrvkJon7yW', 'title' => 'Shipped', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'qsLpFtrvkJon7yW', 'title' => 'Shipped', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'qsLpFtrvkJon7yW', 'title' => 'Shipped', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'Haia2qvAFbJfBlG', 'title' => 'รวม', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'Haia2qvAFbJfBlG', 'title' => 'Total', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'Haia2qvAFbJfBlG', 'title' => 'Total', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'Haia2qvAFbJfBlG', 'title' => 'Total', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'kUP6dQ7fL9vPvsr', 'title' => 'การชำระเงิน', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'kUP6dQ7fL9vPvsr', 'title' => 'Payment', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'kUP6dQ7fL9vPvsr', 'title' => 'Payment', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'kUP6dQ7fL9vPvsr', 'title' => 'Payment', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'ORYUSsKvBhqEQDl', 'title' => 'ระบุวิธีการชำระเงิน', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'ORYUSsKvBhqEQDl', 'title' => 'Specify payment method', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'ORYUSsKvBhqEQDl', 'title' => 'Specify payment method', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'ORYUSsKvBhqEQDl', 'title' => 'Specify payment method', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'U9wUDU7CBossWRy', 'title' => 'โอนเงิน', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'U9wUDU7CBossWRy', 'title' => 'Transfer money', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'U9wUDU7CBossWRy', 'title' => 'Transfer money', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'U9wUDU7CBossWRy', 'title' => 'Transfer money', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'Kv2QOmFVbdg5icr', 'title' => 'ชำระเงินปลายทาง', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'Kv2QOmFVbdg5icr', 'title' => 'Cash on delivery', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'Kv2QOmFVbdg5icr', 'title' => 'Cash on delivery', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'Kv2QOmFVbdg5icr', 'title' => 'Cash on delivery', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'i83LfmDE84SJFMS', 'title' => 'อัพโหลดสลิป', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'i83LfmDE84SJFMS', 'title' => 'Upload slip', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'i83LfmDE84SJFMS', 'title' => 'Upload slip', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'i83LfmDE84SJFMS', 'title' => 'Upload slip', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'QUOb8F327AEoVCH', 'title' => 'กรุณาอัพโหลดสลิปเพื่อยืนยันการชำระเงินของคุณ', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'QUOb8F327AEoVCH', 'title' => 'Please upload slip to verify your payment.', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'QUOb8F327AEoVCH', 'title' => 'Please upload slip to verify your payment.', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'QUOb8F327AEoVCH', 'title' => 'Please upload slip to verify your payment.', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'PGPC1VPte0N2dM5', 'title' => 'ไฟล์ที่รองรับ JPG,PNG ขนาดสูงสุด 2MB', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'PGPC1VPte0N2dM5', 'title' => 'File Supported JPG,PNG maximum size 2MB', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'PGPC1VPte0N2dM5', 'title' => 'File Supported JPG,PNG maximum size 2MB', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'PGPC1VPte0N2dM5', 'title' => 'File Supported JPG,PNG maximum size 2MB', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'VpSaD6RRUra02EC', 'title' => 'เปิดไฟล์', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'VpSaD6RRUra02EC', 'title' => 'Browse file', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'VpSaD6RRUra02EC', 'title' => 'Browse file', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'VpSaD6RRUra02EC', 'title' => 'Browse file', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'cS4O1JRbehVEk3t', 'title' => 'ถ่ายรูป', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'cS4O1JRbehVEk3t', 'title' => 'Take a photo', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'cS4O1JRbehVEk3t', 'title' => 'Take a photo', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'cS4O1JRbehVEk3t', 'title' => 'Take a photo', 'language' => 'ind', 'page_control' => '13'],
            ['param' => '7z14qgoHMPZl8ks', 'title' => 'ราคารวม', 'language' => 'th', 'page_control' => '13'],
            ['param' => '7z14qgoHMPZl8ks', 'title' => 'Total', 'language' => 'en', 'page_control' => '13'],
            ['param' => '7z14qgoHMPZl8ks', 'title' => 'Total', 'language' => 'kh', 'page_control' => '13'],
            ['param' => '7z14qgoHMPZl8ks', 'title' => 'Total', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'tk5I9UXxkKmoRTq', 'title' => 'ราคานี้รวมค่าใช้จ่ายทั้งหมดแล้ว', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'tk5I9UXxkKmoRTq', 'title' => 'The price includes all expenses.', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'tk5I9UXxkKmoRTq', 'title' => 'The price includes all expenses.', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'tk5I9UXxkKmoRTq', 'title' => 'The price includes all expenses.', 'language' => 'ind', 'page_control' => '13'],
            ['param' => '8Fpiey7pzpWEqBa', 'title' => 'ยืนยัน', 'language' => 'th', 'page_control' => '13'],
            ['param' => '8Fpiey7pzpWEqBa', 'title' => 'Confirm', 'language' => 'en', 'page_control' => '13'],
            ['param' => '8Fpiey7pzpWEqBa', 'title' => 'Confirm', 'language' => 'kh', 'page_control' => '13'],
            ['param' => '8Fpiey7pzpWEqBa', 'title' => 'Confirm', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'mFRfK4X9XlJiSun', 'title' => 'ที่อยู่การจัดส่ง', 'language' => 'th', 'page_control' => '14'],
            ['param' => 'mFRfK4X9XlJiSun', 'title' => 'Delivery Address', 'language' => 'en', 'page_control' => '14'],
            ['param' => 'mFRfK4X9XlJiSun', 'title' => 'Delivery Address', 'language' => 'kh', 'page_control' => '14'],
            ['param' => 'mFRfK4X9XlJiSun', 'title' => 'Delivery Address', 'language' => 'ind', 'page_control' => '14'],
            ['param' => '0un6xgfazoC’c&', 'title' =>  'ที่อยู่', 'language' => 'th', 'page_control' => '14'],
            ['param' => '0un6xgfazoC’c&', 'title' =>  'Address', 'language' => 'en', 'page_control' => '14'],
            ['param' => '0un6xgfazoC’c&', 'title' =>  'Address', 'language' => 'kh', 'page_control' => '14'],
            ['param' => '0un6xgfazoC’c&', 'title' =>  'Address', 'language' => 'ind', 'page_control' => '14'],
            ['param' => 'Uxd43rYTfBOjjJA', 'title' => 'เบอร์โทร', 'language' => 'th', 'page_control' => '14'],
            ['param' => 'Uxd43rYTfBOjjJA', 'title' => 'Your Phone Number', 'language' => 'en', 'page_control' => '14'],
            ['param' => 'Uxd43rYTfBOjjJA', 'title' => 'Your Phone Number', 'language' => 'kh', 'page_control' => '14'],
            ['param' => 'Uxd43rYTfBOjjJA', 'title' => 'Your Phone Number', 'language' => 'ind', 'page_control' => '14'],
            ['param' => '787WjhhsYuNiIEY', 'title' => 'เลือกสาขา', 'language' => 'th', 'page_control' => '14'],
            ['param' => '787WjhhsYuNiIEY', 'title' => 'Choose a Branch', 'language' => 'en', 'page_control' => '14'],
            ['param' => '787WjhhsYuNiIEY', 'title' => 'Choose a Branch', 'language' => 'kh', 'page_control' => '14'],
            ['param' => '787WjhhsYuNiIEY', 'title' => 'Choose a Branch', 'language' => 'ind', 'page_control' => '14'],
            ['param' => 'JBcoUyvEt4jKaH1', 'title' => 'เวลาการจัดส่ง', 'language' => 'th', 'page_control' => '14'],
            ['param' => 'JBcoUyvEt4jKaH1', 'title' => 'Shipping Time', 'language' => 'en', 'page_control' => '14'],
            ['param' => 'JBcoUyvEt4jKaH1', 'title' => 'Shipping Time', 'language' => 'kh', 'page_control' => '14'],
            ['param' => 'JBcoUyvEt4jKaH1', 'title' => 'Shipping Time', 'language' => 'ind', 'page_control' => '14'],
            ['param' => 'bF1J4QuMHnHJrRl', 'title' => 'เวลาปัจจุบัน', 'language' => 'th', 'page_control' => '14'],
            ['param' => 'bF1J4QuMHnHJrRl', 'title' => 'Now', 'language' => 'en', 'page_control' => '14'],
            ['param' => 'bF1J4QuMHnHJrRl', 'title' => 'Now', 'language' => 'kh', 'page_control' => '14'],
            ['param' => 'bF1J4QuMHnHJrRl', 'title' => 'Now', 'language' => 'ind', 'page_control' => '14'],
            ['param' => 'ZNn1o6seq3qvI3I', 'title' => 'เลือกเวลาจัดส่ง', 'language' => 'th', 'page_control' => '14'],
            ['param' => 'ZNn1o6seq3qvI3I', 'title' => 'Ship Time', 'language' => 'en', 'page_control' => '14'],
            ['param' => 'ZNn1o6seq3qvI3I', 'title' => 'Ship Time', 'language' => 'kh', 'page_control' => '14'],
            ['param' => 'ZNn1o6seq3qvI3I', 'title' => 'Ship Time', 'language' => 'ind', 'page_control' => '14'],
            ['param' => 'PaM4tOGaL3rbSvR', 'title' => 'เลือกวันและเวลา :', 'language' => 'th', 'page_control' => '14'],
            ['param' => 'PaM4tOGaL3rbSvR', 'title' => 'Select a date and time :', 'language' => 'en', 'page_control' => '14'],
            ['param' => 'PaM4tOGaL3rbSvR', 'title' => 'Select a date and time :', 'language' => 'kh', 'page_control' => '14'],
            ['param' => 'PaM4tOGaL3rbSvR', 'title' => 'Select a date and time :', 'language' => 'ind', 'page_control' => '14'],
            ['param' => 'tIESWu7iMVDFlbb', 'title' => 'ถัดไป', 'language' => 'th', 'page_control' => '14'],
            ['param' => 'tIESWu7iMVDFlbb', 'title' => 'Next', 'language' => 'en', 'page_control' => '14'],
            ['param' => 'tIESWu7iMVDFlbb', 'title' => 'Next', 'language' => 'kh', 'page_control' => '14'],
            ['param' => 'tIESWu7iMVDFlbb', 'title' => 'Next', 'language' => 'ind', 'page_control' => '14'],
            ['param' => 'gcQtJs1mG7LpSH9', 'title' => 'ประเภทรายการอาหาร', 'language' => 'th', 'page_control' => '15'],
            ['param' => 'gcQtJs1mG7LpSH9', 'title' => 'Product Category', 'language' => 'en', 'page_control' => '15'],
            ['param' => 'gcQtJs1mG7LpSH9', 'title' => 'Product Category', 'language' => 'kh', 'page_control' => '15'],
            ['param' => 'gcQtJs1mG7LpSH9', 'title' => 'Product Category', 'language' => 'ind', 'page_control' => '15'],
            ['param' => 'yC2SXD73c5EJdak', 'title' => 'ราคา', 'language' => 'th', 'page_control' => '15'],
            ['param' => 'yC2SXD73c5EJdak', 'title' => 'Price', 'language' => 'en', 'page_control' => '15'],
            ['param' => 'yC2SXD73c5EJdak', 'title' => 'Price', 'language' => 'kh', 'page_control' => '15'],
            ['param' => 'yC2SXD73c5EJdak', 'title' => 'Price', 'language' => 'ind', 'page_control' => '15'],
            ['param' => '9vfWGKhNbMmSNLn', 'title' => 'เกี่ยวกับสินค้า', 'language' => 'th', 'page_control' => '15'],
            ['param' => '9vfWGKhNbMmSNLn', 'title' => 'About Products', 'language' => 'en', 'page_control' => '15'],
            ['param' => '9vfWGKhNbMmSNLn', 'title' => 'About Products', 'language' => 'kh', 'page_control' => '15'],
            ['param' => '9vfWGKhNbMmSNLn', 'title' => 'About Products', 'language' => 'ind', 'page_control' => '15'],
            ['param' => 'Q3PcqJGe9tbPH15', 'title' => 'จำนวน', 'language' => 'th', 'page_control' => '15'],
            ['param' => 'Q3PcqJGe9tbPH15', 'title' => 'Quantity', 'language' => 'en', 'page_control' => '15'],
            ['param' => 'Q3PcqJGe9tbPH15', 'title' => 'Quantity', 'language' => 'kh', 'page_control' => '15'],
            ['param' => 'Q3PcqJGe9tbPH15', 'title' => 'Quantity', 'language' => 'ind', 'page_control' => '15'],
            ['param' => 'RyXtgXIWNjciCAN', 'title' => 'เพิ่มในตะกร้า', 'language' => 'th', 'page_control' => '15'],
            ['param' => 'RyXtgXIWNjciCAN', 'title' => 'Add to cart', 'language' => 'en', 'page_control' => '15'],
            ['param' => 'RyXtgXIWNjciCAN', 'title' => 'Add to cart', 'language' => 'kh', 'page_control' => '15'],
            ['param' => 'RyXtgXIWNjciCAN', 'title' => 'Add to cart', 'language' => 'ind', 'page_control' => '15'],
            ['param' => 'NRFRBwQXA9VONsE', 'title' => 'บาท', 'language' => 'th', 'page_control' => '4'],
            ['param' => 'NRFRBwQXA9VONsE', 'title' => '$', 'language' => 'en', 'page_control' => '4'],
            ['param' => 'NRFRBwQXA9VONsE', 'title' => '$', 'language' => 'kh', 'page_control' => '4'],
            ['param' => 'NRFRBwQXA9VONsE', 'title' => '$', 'language' => 'ind', 'page_control' => '4'],
            ['param' => '4GX41aMsumE0xYz', 'title' => 'ราคายังไม่รวมส่วนลดและค่าขนส่ง', 'language' => 'th', 'page_control' => '17'],
            ['param' => '4GX41aMsumE0xYz', 'title' => 'Discounts and shipping are not included.', 'language' => 'en', 'page_control' => '17'],
            ['param' => '4GX41aMsumE0xYz', 'title' => 'Discounts and shipping are not included.', 'language' => 'kh', 'page_control' => '17'],
            ['param' => '4GX41aMsumE0xYz', 'title' => 'Discounts and shipping are not included.', 'language' => 'ind', 'page_control' => '17'],
            ['param' => 'SLczhvM483BnChZ', 'title' => 'เลขออเดอร์', 'language' => 'th', 'page_control' => '17'],
            ['param' => 'SLczhvM483BnChZ', 'title' => 'Order', 'language' => 'en', 'page_control' => '17'],
            ['param' => 'SLczhvM483BnChZ', 'title' => 'Order', 'language' => 'kh', 'page_control' => '17'],
            ['param' => 'SLczhvM483BnChZ', 'title' => 'Order', 'language' => 'ind', 'page_control' => '17'],
            ['param' => '7Yhxn0M6FyeGl3Z', 'title' => 'ที่อยู่การจัดส่ง', 'language' => 'th', 'page_control' => '13'],
            ['param' => '7Yhxn0M6FyeGl3Z', 'title' => 'Delivery Address', 'language' => 'en', 'page_control' => '13'],
            ['param' => '7Yhxn0M6FyeGl3Z', 'title' => 'Delivery Address', 'language' => 'kh', 'page_control' => '13'],
            ['param' => '7Yhxn0M6FyeGl3Z', 'title' => 'Delivery Address', 'language' => 'ind', 'page_control' => '13'],
            ['param' => '5TOmOsWuMrugmS6', 'title' => 'เวลาการจัดส่ง', 'language' => 'th', 'page_control' => '13'],
            ['param' => '5TOmOsWuMrugmS6', 'title' => 'Shipping Time', 'language' => 'en', 'page_control' => '13'],
            ['param' => '5TOmOsWuMrugmS6', 'title' => 'Shipping Time', 'language' => 'kh', 'page_control' => '13'],
            ['param' => '5TOmOsWuMrugmS6', 'title' => 'Shipping Time', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'SSLvj3L2arv0n4S', 'title' => 'รายการอาหาร', 'language' => 'th', 'page_control' => '13'],
            ['param' => 'SSLvj3L2arv0n4S', 'title' => 'Foods list', 'language' => 'en', 'page_control' => '13'],
            ['param' => 'SSLvj3L2arv0n4S', 'title' => 'Foods list', 'language' => 'kh', 'page_control' => '13'],
            ['param' => 'SSLvj3L2arv0n4S', 'title' => 'Foods list', 'language' => 'ind', 'page_control' => '13'],
            ['param' => 'VA387Rm5cV2ee3m', 'title' => 'แก้ไขข้อมูลหรือตรวจสอบคำสั่งซื้อของคุณ', 'language' => 'th', 'page_control' => '1'],
            ['param' => 'VA387Rm5cV2ee3m', 'title' => 'Choose to edit information or review your order.', 'language' => 'en', 'page_control' => '1'],
            ['param' => 'VA387Rm5cV2ee3m', 'title' => 'Choose to edit information or review your order.', 'language' => 'kh', 'page_control' => '1'],
            ['param' => 'VA387Rm5cV2ee3m', 'title' => 'Choose to edit information or review your order.', 'language' => 'ind', 'page_control' => '1'],
            ['param' => '0Mi8LiRItTdSWOY', 'title' => 'ข้อมูลส่วนตัว', 'language' => 'th', 'page_control' => '1'],
            ['param' => '0Mi8LiRItTdSWOY', 'title' => 'Information', 'language' => 'en', 'page_control' => '1'],
            ['param' => '0Mi8LiRItTdSWOY', 'title' => 'Information', 'language' => 'kh', 'page_control' => '1'],
            ['param' => '0Mi8LiRItTdSWOY', 'title' => 'Information', 'language' => 'ind', 'page_control' => '1'],
            ['param' => 'U4KviO5js49LqVr', 'title' => 'ประวัติการสั่งซื้อ', 'language' => 'th', 'page_control' => '1'],
            ['param' => 'U4KviO5js49LqVr', 'title' => 'Order history', 'language' => 'en', 'page_control' => '1'],
            ['param' => 'U4KviO5js49LqVr', 'title' => 'Order history', 'language' => 'kh', 'page_control' => '1'],
            ['param' => 'U4KviO5js49LqVr', 'title' => 'Order history', 'language' => 'ind', 'page_control' => '1'],
            ['param' => 'PVVUFd0uFvJBwtg', 'title' => 'ออกจากระบบ', 'language' => 'th', 'page_control' => '1'],
            ['param' => 'PVVUFd0uFvJBwtg', 'title' => 'SIGN OUT', 'language' => 'en', 'page_control' => '1'],
            ['param' => 'PVVUFd0uFvJBwtg', 'title' => 'SIGN OUT', 'language' => 'kh', 'page_control' => '1'],
            ['param' => 'PVVUFd0uFvJBwtg', 'title' => 'SIGN OUT', 'language' => 'ind', 'page_control' => '1'],
            ['param' => '8G3Qtqce5rVIn8r', 'title' => 'สั่งซื้อเพิ่มเติม', 'language' => 'th', 'page_control' => '1'],
            ['param' => '8G3Qtqce5rVIn8r', 'title' => 'Order more', 'language' => 'en', 'page_control' => '1'],
            ['param' => '8G3Qtqce5rVIn8r', 'title' => 'Order more', 'language' => 'kh', 'page_control' => '1'],
            ['param' => '8G3Qtqce5rVIn8r', 'title' => 'Order more', 'language' => 'ind', 'page_control' => '1'],
            ['param' => 'bgWLRdITRIrMRDC', 'title' => 'ข้อมูลส่วนตัว', 'language' => 'th', 'page_control' => '2'],
            ['param' => 'bgWLRdITRIrMRDC', 'title' => 'Personal Information', 'language' => 'en', 'page_control' => '2'],
            ['param' => 'bgWLRdITRIrMRDC', 'title' => 'Personal Information', 'language' => 'kh', 'page_control' => '2'],
            ['param' => 'bgWLRdITRIrMRDC', 'title' => 'Personal Information', 'language' => 'ind', 'page_control' => '2'],
            ['param' => 'QlHspnlfBPJ3nge', 'title' => 'ชื่อ', 'language' => 'th', 'page_control' => '2'],
            ['param' => 'QlHspnlfBPJ3nge', 'title' => 'Name', 'language' => 'en', 'page_control' => '2'],
            ['param' => 'QlHspnlfBPJ3nge', 'title' => 'Name', 'language' => 'kh', 'page_control' => '2'],
            ['param' => 'QlHspnlfBPJ3nge', 'title' => 'Name', 'language' => 'ind', 'page_control' => '2'],
            ['param' => 'oJA9NRRUOyiSLJx', 'title' => 'เบอร์โทร', 'language' => 'th', 'page_control' => '2'],
            ['param' => 'oJA9NRRUOyiSLJx', 'title' => 'Phone Number', 'language' => 'en', 'page_control' => '2'],
            ['param' => 'oJA9NRRUOyiSLJx', 'title' => 'Phone Number', 'language' => 'kh', 'page_control' => '2'],
            ['param' => 'oJA9NRRUOyiSLJx', 'title' => 'Phone Number', 'language' => 'ind', 'page_control' => '2'],
            ['param' => 'm75qxWr3Yb99L8F', 'title' => 'อีเมล', 'language' => 'th', 'page_control' => '2'],
            ['param' => 'm75qxWr3Yb99L8F', 'title' => 'E-mail', 'language' => 'en', 'page_control' => '2'],
            ['param' => 'm75qxWr3Yb99L8F', 'title' => 'E-mail', 'language' => 'kh', 'page_control' => '2'],
            ['param' => 'm75qxWr3Yb99L8F', 'title' => 'E-mail', 'language' => 'ind', 'page_control' => '2'],
            ['param' => '7ADqZahT2HBmlwB', 'title' => 'ไลน์ไอดี', 'language' => 'th', 'page_control' => '2'],
            ['param' => '7ADqZahT2HBmlwB', 'title' => 'Line ID', 'language' => 'en', 'page_control' => '2'],
            ['param' => '7ADqZahT2HBmlwB', 'title' => 'Line ID', 'language' => 'kh', 'page_control' => '2'],
            ['param' => '7ADqZahT2HBmlwB', 'title' => 'Line ID', 'language' => 'ind', 'page_control' => '2'],
            ['param' => 'KPu4GXZqSGgPLfK', 'title' => 'ที่อยู่', 'language' => 'th', 'page_control' => '2'],
            ['param' => 'KPu4GXZqSGgPLfK', 'title' => 'Address', 'language' => 'en', 'page_control' => '2'],
            ['param' => 'KPu4GXZqSGgPLfK', 'title' => 'Address', 'language' => 'kh', 'page_control' => '2'],
            ['param' => 'KPu4GXZqSGgPLfK', 'title' => 'Address', 'language' => 'ind', 'page_control' => '2'],
            ['param' => 'n9EtCIMfe2YkK87', 'title' => 'เปลี่ยนรหัสผ่าน', 'language' => 'th', 'page_control' => '2'],
            ['param' => 'n9EtCIMfe2YkK87', 'title' => 'Change Password', 'language' => 'en', 'page_control' => '2'],
            ['param' => 'n9EtCIMfe2YkK87', 'title' => 'Change Password', 'language' => 'kh', 'page_control' => '2'],
            ['param' => 'n9EtCIMfe2YkK87', 'title' => 'Change Password', 'language' => 'ind', 'page_control' => '2'],
            ['param' => 'Ay9U7lreuOhEcxn', 'title' => 'รหัสผ่านปัจจุบัน', 'language' => 'th', 'page_control' => '2'],
            ['param' => 'Ay9U7lreuOhEcxn', 'title' => 'Current Password', 'language' => 'en', 'page_control' => '2'],
            ['param' => 'Ay9U7lreuOhEcxn', 'title' => 'Current Password', 'language' => 'kh', 'page_control' => '2'],
            ['param' => 'Ay9U7lreuOhEcxn', 'title' => 'Current Password', 'language' => 'ind', 'page_control' => '2'],
            ['param' => 'Mr3SswCXQenfeFc', 'title' => 'รหัสผ่านใหม่', 'language' => 'th', 'page_control' => '2'],
            ['param' => 'Mr3SswCXQenfeFc', 'title' => 'New Password', 'language' => 'en', 'page_control' => '2'],
            ['param' => 'Mr3SswCXQenfeFc', 'title' => 'New Password', 'language' => 'kh', 'page_control' => '2'],
            ['param' => 'Mr3SswCXQenfeFc', 'title' => 'New Password', 'language' => 'ind', 'page_control' => '2'],
            ['param' => 'cNIUl7XH9EwFMh8', 'title' => 'ยืนยันรหัสผ่านใหม่', 'language' => 'th', 'page_control' => '2'],
            ['param' => 'cNIUl7XH9EwFMh8', 'title' => 'Retype New Password', 'language' => 'en', 'page_control' => '2'],
            ['param' => 'cNIUl7XH9EwFMh8', 'title' => 'Retype New Password', 'language' => 'kh', 'page_control' => '2'],
            ['param' => 'cNIUl7XH9EwFMh8', 'title' => 'Retype New Password', 'language' => 'ind', 'page_control' => '2'],
            ['param' => '1aI6GTGuyzZBu3G', 'title' => 'ยกเลิก', 'language' => 'th', 'page_control' => '2'],
            ['param' => '1aI6GTGuyzZBu3G', 'title' => 'DISCARD CHAGES', 'language' => 'en', 'page_control' => '2'],
            ['param' => '1aI6GTGuyzZBu3G', 'title' => 'DISCARD CHAGES', 'language' => 'kh', 'page_control' => '2'],
            ['param' => '1aI6GTGuyzZBu3G', 'title' => 'DISCARD CHAGES', 'language' => 'ind', 'page_control' => '2'],
            ['param' => 'sRMDcYUyI7XtLHK', 'title' => 'บันทึก', 'language' => 'th', 'page_control' => '2'],
            ['param' => 'sRMDcYUyI7XtLHK', 'title' => 'SAVE CHAGES', 'language' => 'en', 'page_control' => '2'],
            ['param' => 'sRMDcYUyI7XtLHK', 'title' => 'SAVE CHAGES', 'language' => 'kh', 'page_control' => '2'],
            ['param' => 'sRMDcYUyI7XtLHK', 'title' => 'SAVE CHAGES', 'language' => 'ind', 'page_control' => '2'],
            ['param' => 'KZci2Y5o20MfBKC', 'title' => 'บันทึกการเปลี่ยนแปลง', 'language' => 'th', 'page_control' => '2'],
            ['param' => 'KZci2Y5o20MfBKC', 'title' => 'Save your changes', 'language' => 'en', 'page_control' => '2'],
            ['param' => 'KZci2Y5o20MfBKC', 'title' => 'Save your changes', 'language' => 'kh', 'page_control' => '2'],
            ['param' => 'KZci2Y5o20MfBKC', 'title' => 'Save your changes', 'language' => 'ind', 'page_control' => '2'],
            ['param' => 'FARUE6MKaDcgh2g', 'title' => 'วันที่ทำรายการ', 'language' => 'th', 'page_control' => '4'],
            ['param' => 'FARUE6MKaDcgh2g', 'title' => 'Transaction Date', 'language' => 'en', 'page_control' => '4'],
            ['param' => 'FARUE6MKaDcgh2g', 'title' => 'Transaction Date', 'language' => 'kh', 'page_control' => '4'],
            ['param' => 'FARUE6MKaDcgh2g', 'title' => 'Transaction Date', 'language' => 'ind', 'page_control' => '4'],
            ['param' => 'eotQuhE51ZJuLnz', 'title' => 'สถานะ', 'language' => 'th', 'page_control' => '4'],
            ['param' => 'eotQuhE51ZJuLnz', 'title' => 'Status', 'language' => 'en', 'page_control' => '4'],
            ['param' => 'eotQuhE51ZJuLnz', 'title' => 'Status', 'language' => 'kh', 'page_control' => '4'],
            ['param' => 'eotQuhE51ZJuLnz', 'title' => 'Status', 'language' => 'ind', 'page_control' => '4'],
            ['param' => '0ItP0i19dNPjRQW', 'title' => 'เลขออเดอร์', 'language' => 'th', 'page_control' => '4'],
            ['param' => '0ItP0i19dNPjRQW', 'title' => 'Order Number', 'language' => 'en', 'page_control' => '4'],
            ['param' => '0ItP0i19dNPjRQW', 'title' => 'Order Number', 'language' => 'kh', 'page_control' => '4'],
            ['param' => '0ItP0i19dNPjRQW', 'title' => 'Order Number', 'language' => 'ind', 'page_control' => '4'],
            ['param' => 'tXHgpzw9H4sZA1w', 'title' => 'เวลาการจัดส่ง', 'language' => 'th', 'page_control' => '4'],
            ['param' => 'tXHgpzw9H4sZA1w', 'title' => 'Shipping Time', 'language' => 'en', 'page_control' => '4'],
            ['param' => 'tXHgpzw9H4sZA1w', 'title' => 'Shipping Time', 'language' => 'kh', 'page_control' => '4'],
            ['param' => 'tXHgpzw9H4sZA1w', 'title' => 'Shipping Time', 'language' => 'ind', 'page_control' => '4'],
            ['param' => '411udf8l0z1YClt', 'title' => 'ประเภทรายการ', 'language' => 'th', 'page_control' => '4'],
            ['param' => '411udf8l0z1YClt', 'title' => 'Type List', 'language' => 'en', 'page_control' => '4'],
            ['param' => '411udf8l0z1YClt', 'title' => 'Type List', 'language' => 'kh', 'page_control' => '4'],
            ['param' => '411udf8l0z1YClt', 'title' => 'Type List', 'language' => 'ind', 'page_control' => '4'],
            ['param' => 'T50shTDWtbGUrLS', 'title' => 'ที่อยู่การจัดส่ง', 'language' => 'th', 'page_control' => '4'],
            ['param' => 'T50shTDWtbGUrLS', 'title' => 'Delivery Address', 'language' => 'en', 'page_control' => '4'],
            ['param' => 'T50shTDWtbGUrLS', 'title' => 'Delivery Address', 'language' => 'kh', 'page_control' => '4'],
            ['param' => 'T50shTDWtbGUrLS', 'title' => 'Delivery Address', 'language' => 'ind', 'page_control' => '4'],
            ['param' => 'd8gSfZLQSRZyvHS', 'title' => 'ราคาการสั่งซื้อ', 'language' => 'th', 'page_control' => '4'],
            ['param' => 'd8gSfZLQSRZyvHS', 'title' => 'sum buy', 'language' => 'en', 'page_control' => '4'],
            ['param' => 'd8gSfZLQSRZyvHS', 'title' => 'sum buy', 'language' => 'kh', 'page_control' => '4'],
            ['param' => 'd8gSfZLQSRZyvHS', 'title' => 'sum buy', 'language' => 'ind', 'page_control' => '4'],
            ['param' => 've7LTX3JrNH6W3l', 'title' => 'รายละเอียด', 'language' => 'th', 'page_control' => '4'],
            ['param' => 've7LTX3JrNH6W3l', 'title' => 'ORDER DETAIL', 'language' => 'en', 'page_control' => '4'],
            ['param' => 've7LTX3JrNH6W3l', 'title' => 'ORDER DETAIL', 'language' => 'kh', 'page_control' => '4'],
            ['param' => 've7LTX3JrNH6W3l', 'title' => 'ORDER DETAIL', 'language' => 'ind', 'page_control' => '4'],
            ['param' => 'RiwAIkksVo7vGHS', 'title' => 'ที่อยู่', 'language' => 'th', 'page_control' => '4'],
            ['param' => 'RiwAIkksVo7vGHS', 'title' => 'Address', 'language' => 'en', 'page_control' => '4'],
            ['param' => 'RiwAIkksVo7vGHS', 'title' => 'Address', 'language' => 'kh', 'page_control' => '4'],
            ['param' => 'RiwAIkksVo7vGHS', 'title' => 'Address', 'language' => 'ind', 'page_control' => '4'],
            ['param' => 'NEa9oYkheKKEWYm', 'title' => 'รายละเอียดเพิ่มเติม', 'language' => 'th', 'page_control' => '4'],
            ['param' => 'NEa9oYkheKKEWYm', 'title' => 'More Detail', 'language' => 'en', 'page_control' => '4'],
            ['param' => 'NEa9oYkheKKEWYm', 'title' => 'More Detail', 'language' => 'kh', 'page_control' => '4'],
            ['param' => 'NEa9oYkheKKEWYm', 'title' => 'More Detail', 'language' => 'ind', 'page_control' => '4'],
            ['param' => '8Y1gz9oyeblc7gi', 'title' => 'เบอร์โทร', 'language' => 'th', 'page_control' => '4'],
            ['param' => '8Y1gz9oyeblc7gi', 'title' => 'Phone Number', 'language' => 'en', 'page_control' => '4'],
            ['param' => '8Y1gz9oyeblc7gi', 'title' => 'Phone Number', 'language' => 'kh', 'page_control' => '4'],
            ['param' => '8Y1gz9oyeblc7gi', 'title' => 'Phone Number', 'language' => 'ind', 'page_control' => '4'],
            ['param' => 'ZYvWS3fZpZ8BppH', 'title' => 'รูปภาพ', 'language' => 'th', 'page_control' => '4'],
            ['param' => 'ZYvWS3fZpZ8BppH', 'title' => 'Photo', 'language' => 'en', 'page_control' => '4'],
            ['param' => 'ZYvWS3fZpZ8BppH', 'title' => 'Photo', 'language' => 'kh', 'page_control' => '4'],
            ['param' => 'ZYvWS3fZpZ8BppH', 'title' => 'Photo', 'language' => 'ind', 'page_control' => '4'],
            ['param' => 'P8jBIDFhq91sXyl', 'title' => 'หลักฐานการรับส่งสินค้า', 'language' => 'th', 'page_control' =>  '4'],
            ['param' => 'P8jBIDFhq91sXyl', 'title' => 'Photo evidence', 'language' => 'en', 'page_control' =>  '4'],
            ['param' => 'P8jBIDFhq91sXyl', 'title' => 'Photo evidence', 'language' => 'kh', 'page_control' =>  '4'],
            ['param' => 'P8jBIDFhq91sXyl', 'title' => 'Photo evidence', 'language' => 'ind', 'page_control' =>  '4'],
            ['param' => 'tsGd2tnPgp5sQnw', 'title' => 'ไม่พบรายการคำสั่งซื้อ', 'language' => 'th', 'page_control' =>  '4'],
            ['param' => 'tsGd2tnPgp5sQnw', 'title' => 'Order not found', 'language' => 'en', 'page_control' =>  '4'],
            ['param' => 'tsGd2tnPgp5sQnw', 'title' => 'Order not found', 'language' => 'kh', 'page_control' =>  '4'],
            ['param' => 'tsGd2tnPgp5sQnw', 'title' => 'Order not found', 'language' => 'ind', 'page_control' =>  '4'],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('language_configs');
    }
};
