<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $table->id('id');
            $table->string('title');
            $table->integer('cate_id')->default(0);
            $table->text('details')->nullable();
            $table->text('more_details')->nullable();
            $table->integer('price')->default(0);
            $table->integer('page_id')->default(0);
            $table->boolean('display')->default(true);
            $table->boolean('can_wave')->default(false);
            $table->boolean('can_sweet')->default(false);
            $table->integer('price_per_minutes')->default(0);
            $table->integer('round_minutes')->default(0);
            $table->integer('default_minutes')->default(0);
            $table->string('keyword')->nullable();
            $table->string('description')->nullable();
            $table->text('freetag')->nullable();
            $table->string('h1')->nullable();
            $table->string('h2')->nullable()->nullable();
            $table->text('short_url')->nullable();
            $table->string('thumbnail_title')->nullable();
            $table->string('thumbnail_link')->nullable();
            $table->string('thumbnail_size')->nullable();
            $table->string('thumbnail_alt')->nullable();
            $table->string('topic')->nullable();
            $table->text('content')->nullable();
            $table->text('iframe')->nullable();
            $table->text('category')->nullable();
            $table->text('tags')->nullable();
            $table->text('redirect')->nullable();
            $table->text('link_facebook')->nullable();
            $table->text('link_twitter')->nullable();
            $table->text('link_instagram')->nullable();
            $table->text('link_youtube')->nullable();
            $table->text('link_line')->nullable();
            $table->dateTime('date_begin_display')->nullable();
            $table->dateTime('date_end_display')->nullable();
            $table->boolean('status_display')->default(false);
            $table->boolean('pin')->default(false);
            $table->integer('post_view')->default(0);
            $table->integer('priority')->default(0);
            $table->string('meta_tag')->nullable();
            $table->string('meta_title')->nullable();
            $table->string('meta_description')->nullable();
            $table->integer('last_update_by')->nullable();
            $table->string('language');
            $table->boolean('defaults')->default(false);
            $table->unique(['language', 'id']);
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
        });
        DB::statement('ALTER TABLE `products` DROP PRIMARY KEY, ADD PRIMARY KEY (`id`, `language`) USING BTREE');

        DB::table('products')->insert([
            [
                'title' => 'Mix',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 1,
                'page_id' => 9,
                'price' => 0,
                'priority' => 1,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/wash&dry/cotton.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Cotton',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 1,
                'page_id' => 9,
                'price' => 0,
                'priority' => 2,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/wash&dry/cotton.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Sport Wear',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 1,
                'page_id' => 9,
                'price' => 0,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/wash&dry/sport.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Easy Care',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 1,
                'page_id' => 9,
                'price' => 0,
                'priority' => 4,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/wash&dry/easy.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Duvet',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 1,
                'page_id' => 9,
                'price' => 0,
                'priority' => 5,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/wash&dry/duvet.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Delicate',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 1,
                'page_id' => 9,
                'price' => 0,
                'priority' => 6,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/wash&dry/delicate.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Washing',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 2,
                'page_id' => 9,
                'price' => 0,
                'priority' => 7,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/wash&dry/drying.png',
                'short_url' => '/washing/wash',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Drying',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 2,
                'page_id' => 9,
                'price' => 0,
                'priority' => 8,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/wash&dry/drying.png',
                'short_url' => '/washing/dry',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => '10 KG',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 3,
                'page_id' => 10,
                'price' => 70,
                'priority' => 9,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/washing/capacityicon.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => '14 KG',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 3,
                'page_id' => 10,
                'price' => 80,
                'priority' => 10,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/washing/capacityicon.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => '18 KG',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 3,
                'page_id' => 10,
                'price' => 90,
                'priority' => 11,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/washing/capacityicon.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => '23 KG',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 3,
                'page_id' => 10,
                'price' => 110,
                'priority' => 12,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/washing/capacityicon.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Cold',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 4,
                'page_id' => 10,
                'price' => 0,
                'priority' => 13,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/washing/temp2.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Warm',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 4,
                'page_id' => 10,
                'price' => 10,
                'priority' => 14,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/washing/temp2.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Hot',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 4,
                'page_id' => 10,
                'price' => 20,
                'priority' => 15,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/washing/temp3.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => '14 KG',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 3,
                'page_id' => 11,
                'price' => 70,
                'priority' => 16,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/drying/capacityicon.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 10,
                'round_minutes' => 6,
                'default_minutes' => 25,
                'defaults' => true,
            ],
            [
                'title' => '20 KG',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 3,
                'page_id' => 11,
                'price' => 80,
                'priority' => 17,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/drying/capacityicon.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 10,
                'round_minutes' => 5,
                'default_minutes' => 25,
                'defaults' => true,
            ],
            [
                'title' => '23 KG',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 3,
                'page_id' => 11,
                'price' => 110,
                'priority' => 18,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'img/drying/capacityicon.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 10,
                'round_minutes' => 4,
                'default_minutes' => 30,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 6,
                'page_id' => 15,
                'price' => 100,
                'priority' => 1,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish1.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 6,
                'page_id' => 15,
                'price' => 100,
                'priority' => 2,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish1.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 6,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish2.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 6,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish2.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 6,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish3.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 6,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish4.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 6,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish4.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 7,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish4.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 7,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish4.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 8,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish1.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 8,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish1.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 9,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish1.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => true,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 9,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish3.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => true,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 10,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish1.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => true,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 10,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish3.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => true,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 11,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish1.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => false,
                'can_sweet' => true,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
            [
                'title' => 'Lorem ipsum dolore sit',
                'details' => 'lorem dskjewlkr sdipewor sdjwelkrjopsdipower sdl;kwerk,.xcmvsdrwepoir',
                'cate_id' => 11,
                'page_id' => 15,
                'price' => 80,
                'priority' => 3,
                'language' => 'th',
                'thumbnail_title' => '',
                'thumbnail_link' => 'images/foods/dish3.png',
                'short_url' => '',
                'thumbnail_size' => '',
                'can_wave' => true,
                'can_sweet' => false,
                'price_per_minutes' => 0,
                'round_minutes' => 0,
                'default_minutes' => 0,
                'defaults' => true,
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('products');
    }
};
